package noahp78.mods.wdid.modhelpers;

import net.minecraft.block.Block;
import noahp78.mods.wdid.wdid;


public class minecraft {

	
	public static void init(){
		//loads of INIT stuff
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.anvil, "An Anvil is a block that uses the item repair interface to repair and rename items \n, and combine enchantments. The anvil uses a complex XP cost system, where the way the tools are positioned and how many times they are repaired affect their cost.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.beacon, "A Beacon is a block used to provide both a unique landmark, and selected buffs to all players in the vicinity. It is activated by placing it as the final block on top of a pyramid formation made up of one to four levels of mineral blocks: Diamond Blocks, Emerald Blocks, Gold Blocks, or Iron Blocks, in any combination.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.bedrock,"Bedrock is both an indestructible[1] and unmineable block. The primary function of bedrock is to create impassable barriers, both at the bottom of The Overworld and at the top and bottom of The Nether.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockClay,"Clay is a block that is a light-blue/gray recolor of the sand texture. Clay can be found on the surface in groups of varying number usually surrounded by sand. It is usually below water, but is sometimes found exposed in, around or under sand. It was uncommon, but was easier to find than other rare blocks (like gold) due to the fact that one only needs to explore surface-level deserts or beaches to find it.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockDiamond,"Blocks of Diamond (also known as Diamond Blocks) are decorative mineral blocks that do not appear in normally generated maps. They currently serve no crafting purpose, functioning instead as a decorative block and as a means of storing diamonds in a compact fashion.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockEmerald,"Blocks of Emerald (also known as emerald blocks) are decorative mineral blocks that do not naturally generate in maps. Although their primary usage is decoration, they can also be used to store emeralds in a compact fashion and are one of the four mineral blocks that can be used in the construction of beacon pyramids.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockGold,"Blocks of Gold (also known as Gold Blocks) are decorative mineral blocks that do not appear in normally generated maps.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockIron,"Blocks of Iron (also known as Iron Blocks) are decorative mineral blocks made from iron ingots which do not appear in normally generated maps anywhere. Iron blocks have the same texture on all six sides.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockLapis,"Lapis Lazuli Block is a decorative mineral block that is crafted from nine Lapis Lazuli dyes. It is a medium blue color, with darker and lighter blue markings on it. Currently, its only uses are as a decorative block and as a form of storage for Lapis Lazuli dye. It looks very similar to water, which is why it's sometimes used for easily creating water decorations.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockNetherQuartz, "Blocks of Quartz (also known as Quartz Blocks) are mineral blocks crafted from Nether Quartz that are used only for decoration.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockRedstone, "A block of redstone (aka redstone block, redblock) acts as a piston-movable redstone power source which cannot be turned off.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockSnow, "Snow is a full-sized block version of the snow cover. It is crafted from 4 snowballs, allowing the player to create it through their inventory crafting window. One may not reverse the crafting process, but the block may be placed and destroyed with a shovel, yielding 4 snowballs.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.bookShelf, "A Bookshelf serves to enhance an Enchantment Table, as a decoration, or as an inefficient furnace fuel. Bookshelves naturally appear in libraries inside Strongholds and Villages. Breaking a bookshelf will drop three books, but no wood planks.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.brewingStand, "The Brewing Stand is a block used for Brewing Potions and Splash Potions.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.brick, "Brick is a decorative building block that does not naturally spawn anywhere. It is mostly used to make nice looking homes and towers. Since brick is non-flammable, it is often used to make fireplaces. Brick resists explosions no better than cobblestone. A pickaxe must be used to recover the resource of a placed block, but it will take under a second to break. Breaking a block with the player's hand is slow and will not yield the resource.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cactus, "A Cactus (plural Cacti or Cactus) is a Plant block that occurs naturally in deserts and mesas. When any entity, including players and mobs, touches a cactus, a Half Heart of damage is taken (damage is dealt every 0.5 second).");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cake, "Cake is a solid block used as food, and appears as a sponge base topped with white frosting and cherries (or other red substance). It is the only edible block - all other food items must be held in the hand and right-clicked to consume them. Cake cannot be eaten while being held - it must be placed on a suitable block first.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.carpet, "Carpets are thin blocks used for decoration. They are the same thickness as pressure plates. They are useful if you want a carpeted floor without using wool blocks as the material. They have a negligible hitbox, allowing a person to walk over them without elevating 1/16 of a block. This is similar to how pressure plates work, although you cannot fall through a carpet. Carpets can be helpful when carpeting upstairs rooms without the ceiling of the next floor down being partially made of wool.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.carrot, "A Carrot is a food item that can be planted and consumed. When consumed, it restores four hunger points, and restores 4.8 saturation. Carrots can be used to breed Pigs. Carrots are a rare drop from zombies and are found as crops in Villager farms. The Golden Carrot can be used to make Potions of Night Vision and breed Horses.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.chestTrapped, "Trapped Chests are blocks which emit a redstone signal from all sides when opened,[1] at a strength of one block per player using it up to 15 players. The Trapped Chest is characterized by a slight red tint around the latch and a red line on the rim of the opened chest. Trapped Chests can be made into double Trapped Chests, and are able to be placed adjacent to normal chests without interfering, allowing two chests, or double chests, to be placed adjacent to each other. When you open one, a red shading will be visible around the chest inventory.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cloth, "Wool (previously known as cloth) is a block derived from sheep that can be dyed in any of the 16 different colors. Wool blocks are weak, highly flammable, and offer little resistance against explosions.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.coalBlock, "The Block of Coal (also known as Coal Block) is a compact way to store coal, and can be used for decoration and fuel. As a fuel source, it can smelt 80 items, whereas every coal used one-by-one would only result in 72 items smelted. The block of coal itself is flammable, and burns in much the same manner as wood.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cobblestone, "Cobblestone is a common block, used for crafting many tools and items. Its texture resembles an uneven, roughly paved surface. It is obtained by mining stone and apart from tools, it is commonly used to create constructions with medieval appearance such as castles, towers and roads. Silverfish have the ability to enter and hide in cobblestone (along with stone and stone bricks). There is also a mossy variant of cobblestone, known as moss stone.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cobblestoneMossy, "Moss Stone is a block that was first introduced in Survival Test and remains in all later versions of the game. It looks like Cobblestone, but with moss growing on it. Like Cobblestone, on the upper left, there is an 'L' that points to the north and east. Its only use is for construction - often used in combination with normal Cobblestone for decoration purposes, such as to make buildings look older or to make Nether portals more eerie. Moss Stone can be found naturally in Dungeons, Jungle temples and in the form of scattered boulders in Mega Taiga biomes.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cauldron, "A Cauldron is a block that can be filled with water when right-clicked upon with a Water Bucket. When filled, a Cauldron can be used three times to fill three Glass Bottles, or, since 1.4, can be used to wash off the dye from Leather Armor. However, this consumes just as much water as using a water bottle. The Water Bottles, on the other hand, are key ingredients for the Brewing of Potions using a Brewing Stand. A Cauldron is currently—without the use of mods or cheats—the only way to get water into the Nether. Cauldrons can be found in Witch Huts, alongside a crafting table");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.chest, "Chests are blocks that store items. A single chest can store up to 27 stacks of items or blocks and can hold from 0 to 1728 blocks. A large chest is created by placing two chest blocks adjacent to each other, however, large chests cannot be created directly beside each other. Large chests have 54 storage slots and open as a single chest with six rows of slots. A large chest can hold from 0 to 3456 blocks. The top three rows in the interface correspond to the eastern or northern chest block and the bottom three to the southern or western chest block.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cobblestoneWall,"Cobblestone wall is a block designed for decorative purposes such as gardens and are an alternative to fences. There are 2 types: cobblestone walls and mossy cobblestone walls. They work very similarly to fences, as they are 1.5 blocks tall to mobs. Cobblestone walls are more efficient at fencing off mobs than a two-block high cobblestone wall, costing only half as many blocks, and being more space-efficient as well. The drawback, however; is that a skeleton might shoot over the wall, a creeper could explode if a player is standing near the wall or a spider may climb over the wall.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cocoaPlant, "Cocoa Pods are fruits found naturally on the trunk of normal-sized Jungle Trees. Cocoa Pods are a renewable resource, as they grow on and can be planted on a Jungle Log using Cocoa Beans. The player can harvest Cocoa Beans from the fruits, which can be used in further reproduction of Cocoa Pods, as a brown dye, or for Cookies. When harvested, Cocoa Pods will briefly flash red before disappearing and dropping cocoa beans (the amount of beans dropped varies depending on the cocoa pod's stage of growth. See below for the amount of cocoa beans each stage of pod growth yields).");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.commandBlock, "The Command Block is a block made with the intent to support Adventure mode and allows mapmakers to expand the interaction with the player through server commands. The block can run specified server commands when activated by a redstone current. Considering its great power and possibilities, it can't be normally crafted. It is not available in the creative mode inventory either. Only players with sufficient privileges to use the 'give' command: /give <playername> command_block");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.crops, "This block appears when wheat seeds are planted on farmland. This block, when hacked in or obtained using the /give command, has the tooltip name of Crops.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.dirt,"Dirt is a basic block found abundantly in the Overworld. It is found at any altitude, and comprises the majority of the upper terrain layers in most overworld biomes. Dirt can be thought of as a filler block, used during world generation to fill gaps between resources and features and provide shaping material for terrain, but it can also be collected and utilized for building. grass, snow, and mycelium can spread/collect over the top layer of Dirt blocks; mining these will drop ordinary Dirt blocks. Podzol cannot spread to dirt blocks, because it is a variant of the dirt block itself.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.dispenser, "A Dispenser is a special redstone-powered block. When right-clicked, a menu allows you to place items inside it. Each time the block receives power from a redstone circuit, a random item from its inventory drops out. Dispensers resemble furnaces and droppers, but the three blocks have different uses and crafting recipes.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.doorIron,"An Iron Door is only able to be toggled by a switching mechanism. Iron doors can take quite a bit of time to destroy, even with a pickaxe. To destroy them more quickly, simply break the block beneath the door. Builders can discourage this by placing lava at the top of a 1x1 shaft above the door, and/or by placing the door on top of an obsidian block (or bedrock, if you are in creative mode).Since villagers cannot operate buttons or levers and zombies cannot break them, iron doors can be used to lock a house in a generated village.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.doorWood, "Using the right mouse button on a Wooden Door will shift it from one state to another allowing or preventing passage. They may also be opened by using levers, buttons, pressure plates, or redstone.Since zombies will only pound on or attempt to break down a Wooden Door when it is shut, any door placed so that its open state prevents passage, zombies will be unable to break down the door, but will wait in front of it. This method is useful for protecting villages or the home of the player. Note that this will also prevent your dogs and cats from pathfinding through the door, so you will need to lead them in or out with leads, or convince them to teleport. It will also make use of redstone or switches far more difficult, as pressure plates and the like will leave the door closed (that is, ajar) behind you.A wooden door can also be protected more obviously, but without the above disadvantages, by putting a fence gate in front (outside) of it .");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.dragonEgg, "A dragon egg is a block that spawns on top of the bedrock portal created by the defeat of the Ender Dragon in The End. When the player clicks the egg, it will teleport several blocks away (in Creative mode, it will break instead). They currently have no explicit purpose, but are tricky to collect. The preferred way to pick up the egg is to use a piston to push it off of the bedrock pillar atop the portal, causing it to drop as an item that can be placed in the player's inventory. The portal underneath should be covered with blocks, however, before the piston is powered or else the egg will fall into the portal.They currently serve no purpose, other than as a trophy or decoration.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.dropper, "The dropper is a block that drops an item from its inventory as an entity (as if it were dropped by the player) each time it is powered. If there is a block with an inventory immediately in front of the dropper when it is powered, it will instead store the item within the Tile Entity associated with that block. A dropper can drop items through a glass block in front of it.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.enchantmentTable, "An enchantment table is a block that allows players to spend their experience point levels to enchant tools, books and armor. Enchanting works in three stages. The sprites and icons of enchanted items have a purple luminescence.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.enderChest, "Ender Chests are a type of chest that can store items. They function the same as normal chests, except that their contents are shared across all other Ender Chests placed anywhere, even in different dimensions.");
		//Extending Upon this class is easy. Just call noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockname, "Info string")
		
	}
}
