package noahp78.mods.wdid.modhelpers;

import net.minecraft.block.Block;
import noahp78.mods.wdid.wdid;


public class minecraft {

	
	public static void init(){
		//loads of INIT stuff
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.anvil, "An Anvil is a block that uses the item repair interface to repair and rename items \n, and combine enchantments. The anvil uses a complex XP cost system, where the way the tools are positioned and how many times they are repaired affect their cost.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.beacon, "A Beacon is a block used to provide both a unique landmark, and selected buffs to all players in the vicinity. It is activated by placing it as the final block on top of a pyramid formation made up of one to four levels of mineral blocks: Diamond Blocks, Emerald Blocks, Gold Blocks, or Iron Blocks, in any combination.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.bedrock,"Bedrock is both an indestructible[1] and unmineable block. The primary function of bedrock is to create impassable barriers, both at the bottom of The Overworld and at the top and bottom of The Nether.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockClay,"Clay is a block that is a light-blue/gray recolor of the sand texture. Clay can be found on the surface in groups of varying number usually surrounded by sand. It is usually below water, but is sometimes found exposed in, around or under sand. It was uncommon, but was easier to find than other rare blocks (like gold) due to the fact that one only needs to explore surface-level deserts or beaches to find it.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockDiamond,"Blocks of Diamond (also known as Diamond Blocks) are decorative mineral blocks that do not appear in normally generated maps. They currently serve no crafting purpose, functioning instead as a decorative block and as a means of storing diamonds in a compact fashion.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockEmerald,"Blocks of Emerald (also known as emerald blocks) are decorative mineral blocks that do not naturally generate in maps. Although their primary usage is decoration, they can also be used to store emeralds in a compact fashion and are one of the four mineral blocks that can be used in the construction of beacon pyramids.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockGold,"Blocks of Gold (also known as Gold Blocks) are decorative mineral blocks that do not appear in normally generated maps.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockIron,"Blocks of Iron (also known as Iron Blocks) are decorative mineral blocks made from iron ingots which do not appear in normally generated maps anywhere. Iron blocks have the same texture on all six sides.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockLapis,"Lapis Lazuli Block is a decorative mineral block that is crafted from nine Lapis Lazuli dyes. It is a medium blue color, with darker and lighter blue markings on it. Currently, its only uses are as a decorative block and as a form of storage for Lapis Lazuli dye. It looks very similar to water, which is why it's sometimes used for easily creating water decorations.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockNetherQuartz, "Blocks of Quartz (also known as Quartz Blocks) are mineral blocks crafted from Nether Quartz that are used only for decoration.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockRedstone, "A block of redstone (aka redstone block, redblock) acts as a piston-movable redstone power source which cannot be turned off.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockSnow, "Snow is a full-sized block version of the snow cover. It is crafted from 4 snowballs, allowing the player to create it through their inventory crafting window. One may not reverse the crafting process, but the block may be placed and destroyed with a shovel, yielding 4 snowballs.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.bookShelf, "A Bookshelf serves to enhance an Enchantment Table, as a decoration, or as an inefficient furnace fuel. Bookshelves naturally appear in libraries inside Strongholds and Villages. Breaking a bookshelf will drop three books, but no wood planks.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.brewingStand, "The Brewing Stand is a block used for Brewing Potions and Splash Potions.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.brick, "Brick is a decorative building block that does not naturally spawn anywhere. It is mostly used to make nice looking homes and towers. Since brick is non-flammable, it is often used to make fireplaces. Brick resists explosions no better than cobblestone. A pickaxe must be used to recover the resource of a placed block, but it will take under a second to break. Breaking a block with the player's hand is slow and will not yield the resource.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cactus, "A Cactus (plural Cacti or Cactus) is a Plant block that occurs naturally in deserts and mesas. When any entity, including players and mobs, touches a cactus, a Half Heart of damage is taken (damage is dealt every 0.5 second).");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cake, "Cake is a solid block used as food, and appears as a sponge base topped with white frosting and cherries (or other red substance). It is the only edible block - all other food items must be held in the hand and right-clicked to consume them. Cake cannot be eaten while being held - it must be placed on a suitable block first.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.carpet, "Carpets are thin blocks used for decoration. They are the same thickness as pressure plates. They are useful if you want a carpeted floor without using wool blocks as the material. They have a negligible hitbox, allowing a person to walk over them without elevating 1/16 of a block. This is similar to how pressure plates work, although you cannot fall through a carpet. Carpets can be helpful when carpeting upstairs rooms without the ceiling of the next floor down being partially made of wool.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.carrot, "A Carrot is a food item that can be planted and consumed. When consumed, it restores four hunger points, and restores 4.8 saturation. Carrots can be used to breed Pigs. Carrots are a rare drop from zombies and are found as crops in Villager farms. The Golden Carrot can be used to make Potions of Night Vision and breed Horses.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.chestTrapped, "Trapped Chests are blocks which emit a redstone signal from all sides when opened,[1] at a strength of one block per player using it up to 15 players. The Trapped Chest is characterized by a slight red tint around the latch and a red line on the rim of the opened chest. Trapped Chests can be made into double Trapped Chests, and are able to be placed adjacent to normal chests without interfering, allowing two chests, or double chests, to be placed adjacent to each other. When you open one, a red shading will be visible around the chest inventory.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cloth, "Wool (previously known as cloth) is a block derived from sheep that can be dyed in any of the 16 different colors. Wool blocks are weak, highly flammable, and offer little resistance against explosions.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.coalBlock, "The Block of Coal (also known as Coal Block) is a compact way to store coal, and can be used for decoration and fuel. As a fuel source, it can smelt 80 items, whereas every coal used one-by-one would only result in 72 items smelted. The block of coal itself is flammable, and burns in much the same manner as wood.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cobblestone, "Cobblestone is a common block, used for crafting many tools and items. Its texture resembles an uneven, roughly paved surface. It is obtained by mining stone and apart from tools, it is commonly used to create constructions with medieval appearance such as castles, towers and roads. Silverfish have the ability to enter and hide in cobblestone (along with stone and stone bricks). There is also a mossy variant of cobblestone, known as moss stone.");
		noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.cobblestoneMossy, "Moss Stone is a block that was first introduced in Survival Test and remains in all later versions of the game. It looks like Cobblestone, but with moss growing on it. Like Cobblestone, on the upper left, there is an 'L' that points to the north and east. Its only use is for construction - often used in combination with normal Cobblestone for decoration purposes, such as to make buildings look older or to make Nether portals more eerie. Moss Stone can be found naturally in Dungeons, Jungle temples and in the form of scattered boulders in Mega Taiga biomes.");
		
								
		//Extending Upon this class is easy. Just call noahp78.mods.wdid.wdid.RegisterBlockInfo(net.minecraft.block.Block.blockname, "Info string")
		
	}
}
